Vagrant.configure("2") do |config|
  # Webservers
  (1..ENV['WEB_SERVER'].to_i).each do |i|
    config.vm.define "webserver#{i}" do |webserver|
      webserver.vm.box = "ubuntu/bionic64" 
      webserver.vm.network "private_network", ip: "10.0.0.#{i + 10}" 
      webserver.vm.provider "virtualbox" do |vb|
        vb.memory = ENV['MEM_WEB']
        vb.cpus = ENV['CPU_WEB']
      end
    end
  end

  # Database servers
  (1..ENV['DB_SERVER'].to_i).each do |i|
    config.vm.define "dbserver#{i}" do |dbserver|
      dbserver.vm.box = "ubuntu/bionic64" 
      dbserver.vm.network "private_network", ip: "10.0.0.#{i + 20}"  
      dbserver.vm.provider "virtualbox" do |vb|
        vb.memory = ENV['MEM_DB']
        vb.cpus = ENV['CPU_DB']
      end
    end
  end

  # Load Balancer
  (1..ENV['LOAD_BALANCER'].to_i).each do |i|
    config.vm.define "loadbalancer#{i}" do |lb|
      lb.vm.box = "ubuntu/bionic64"  
      lb.vm.network "private_network", ip: "10.0.0.#{30 + i}"
      lb.vm.provider "virtualbox" do |vb|
        vb.memory = ENV['MEM_LB']
        vb.cpus = ENV['CPU_LB']
      end
    end
  end
end