---
- hosts: 10.0.0.20
  become: yes
  tasks:
    - name: Update Cache
      apt:
        update_cache: true

    - name: Python-mysql
      apt:
        name: python3-mysqldb
        state: present

    - name: Install libmysqlclient-dev
      apt:
        name: libmysqlclient-dev
        state: present

    - name: Install MYSQL
      apt:
        name: mysql-server
        state: present

    - name: Start MYSQL service
      apt:
        name: mysql
        state: started
        enabled: yes

    - name: Open port 3306 for MYSQL
      community.general.ufw:
        rule: allow
        port: 3306
        proto: tcp
