---
- name: Update Cache
  apt:
    update_cache: true
  become: yes

- name: Install HAProxy
  apt:
    name: haproxy
    state: present
  become: yes

- name: Configure HAProxy
  template:
    src: "~/IAC-2025/ansible/roles/loadbalancer/templates/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  become: yes

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted
  become: yes
