---
- hosts: 10.0.0.22
  become: yes
  tasks:
    - name: Update Cache
      apt:
        update_cache: true

    - name: Install haproxy
      apt:
        name: haproxy
        state: present

    - name: Configure haproxy
      template:
        src: "~/IAC-2025/ansible/roles/loadbalancer/templates/haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"

    - name: haproxy restart
      service:
        name: haproxy
        state: restarted
