# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
#Prevent Vagrant from auto generating SSH-key
  config.ssh.insert_key = false

#Path to generated SSH-key
config.ssh.private_key_path = ["/home/neville/IAC-2025/vagrant/klanten/klantnaam/ssh/klantnaam.pub","~/.vagrant.d/insecure_private_key"]

#Server_variables
  SERVER = ENV['SERVER'].to_i  # Aantal servers
  CPU = ENV['CPU'].to_i        # Aantal CPU's per server
  MEM = ENV['MEM'].to_i        # Geheugen per server (in MB)

# Uitrollen web servers
  (1..SERVER).each do |i|
    config.vm.define "klantnaam-test-web#{i}" do |test_web_config|
    # Gebruik Vagrant box Ubuntu 18.04 Bionic Beaver).
      test_web_config.vm.box = "ubuntu/bionic64"
    # VM hostnaam.
      test_web_config.vm.hostname = "klantnaam-test-web#{i}"
    # VM-netwerkinstellingen.
      test_web_config.vm.network :private_network, ip: "10.0._ip.1#{i}"
    # Kopieer public key naar de geautoriseerde sleutels op de VM.
      test_web_config.vm.provision "file", source: "/home/neville/IAC-2025/vagrant/klanten/klantnaam/ssh/klantnaam.pub", destination: "~/.ssh/authorized_keys"
    # VirtualBox-specifieke instellingen.
      test_web_config.vm.provider "virtualbox" do |test_web_vm|
    # Aantal CPU's per web-vm.    
        test_web_vm.cpus = CPU
    # Hoeveelheid Geheugen (RAM) per web-vm. 
        test_web_vm.memory  = MEM
    # Schakel VirtualBox-GUI uit.
        test_web_vm.gui = false
    #  Instellen vm-naam. 
        test_web_vm.name = "klantnaam-test-web#{i}"
      end
    end
  end
end

 