# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
#Prevent Vagrant from auto generating SSH-key
  config.ssh.insert_key = false

#Path to generated SSH-key
config.ssh.private_key_path = ["/home/neville/IAC-2025/vagrant/klanten/klantnaam/ssh/klantnaam","~/.vagrant.d/insecure_private_key"]

#Server_variables
  SERVER = ENV['SERVER'].to_i  # Aantal servers
  CPU = ENV['CPU'].to_i        # Aantal CPU's per server
  MEM = ENV['MEM'].to_i        # Geheugen per server (in MB)

# Uitrollen web servers
  (1..SERVER).each do |i|
    config.vm.define "klantnaam-prod-web#{i}" do |prod_web_config|
    # Gebruik Vagrant box Ubuntu 18.04 Bionic Beaver).
      prod_web_config.vm.box = "ubuntu/bionic64"
    # VM hostnaam.
      prod_web_config.vm.hostname = "klantnaam-prod-web#{i}"
    # VM-netwerkinstellingen.
      prod_web_config.vm.network :private_network, ip: "10.0._ip.2#{i}"
    # Kopieer public key naar de geautoriseerde sleutels op de VM.
      prod_web_config.vm.provision "file", source: "/home/neville/IAC-2025/vagrant/klanten/klantnaam/ssh/klantnaam.pub", destination: "~/.ssh/authorized_keys"
    # VirtualBox-specifieke instellingen.
      prod_web_config.vm.provider "virtualbox" do |prod_web_vm|
    # Aantal CPU's per web-vm.    
        prod_web_vm.cpus = CPU
    # Hoeveelheid Geheugen (RAM) per web-vm. 
        prod_web_vm.memory  = MEM
    # Schakel VirtualBox-GUI uit.
        prod_web_vm.gui = false
    #  Instellen vm-naam. 
        prod_web_vm.name = "klantnaam-prod-web#{i}"
      end
    end
  end

  # Uitrollen databaseserver(s)
  (1..1).each do |i|
    config.vm.define "klantnaam-prod-db#{i}" do |prod_db_config|
  # Vagrant box Ubuntu 18.04 Bionic Beaver).
      prod_db_config.vm.box = "ubuntu/bionic64"
  # VM hostnaam.
      prod_db_config.vm.hostname = "klantnaam-prod-db#{i}"
  # VM-netwerkinstellingen.
      prod_db_config.vm.network :private_network, ip: "10.0._ip.3#{i}"
  # Kopieer public key naar de geautoriseerde sleutels op de VM.    
      prod_db_config.vm.provision "file", source: "/home/neville/IAC-2025/vagrant/klanten/klantnaam/ssh/klantnaam.pub", destination: "~/.ssh/authorized_keys"
  # VirtualBox-specifieke instellingen.
      prod_db_config.vm.provider "virtualbox" do |prod_db_vm|
  # Aantal CPU's per db-vm.   
      prod_db_vm.cpus = "2"
  # Hoeveelheid Geheugen (RAM) per db-vm.
      prod_db_vm.memory  = "2048"
  # Schakel VirtualBox-GUI uit.
      prod_db_vm.gui = false
  #  Instellen vm-naam.
      prod_db_vm.name = "klantnaam-prod-db#{i}"
      end
    end
  end

  # Uitrollen load balancer(s)
  (1..1).each do |i|
    config.vm.define "klantnaam-prod-lb#{i}" do |prod_lb_config|
  # Vagrant box Ubuntu 18.04 Bionic Beaver). 
      prod_lb_config.vm.box = "ubuntu/bionic64"
  # VM hostnaam.
      prod_lb_config.vm.hostname = "klantnaam-prod-lb#{i}"
  # VM-netwerkinstellingen.
      prod_lb_config.vm.network :private_network, ip: "10.0._ip.4#{i}"
  # Kopieer public key naar de geautoriseerde sleutels op de VM.    
      prod_lb_config.vm.provision "file", source: "/home/neville/IAC-2025/vagrant/klanten/klantnaam/ssh/klantnaam.pub", destination: "~/.ssh/authorized_keys"
  # VirtualBox-specifieke instellingen.    
      prod_lb_config.vm.provider "virtualbox" do |prod_lb_vm|
  # Aantal CPU's per lb-vm.   
        prod_lb_vm.cpus = "2"
  # Hoeveelheid Geheugen (RAM) per lb-vm.
        prod_lb_vm.memory  = "2048"
  # Schakel VirtualBox-GUI uit.
        prod_lb_vm.gui = false
  #  Instellen vm-naam.
        prod_lb_vm.name = "klantnaam-prod-lb#{i}"
      end
    end
  end
end 
