---
- hosts: web_servers
  become: yes
  tasks:
    - name: Update Cache
      apt:
        update_cache: true

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Open port 80 for web traffic
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Install php
      apt:
        name: php
        state: present

    - name: Install php-mysql
      apt:
        name: php-mysql
        state: present

    - name: Install mysql-client
      apt:
        name: mysql-client

    - name: Open port 3306 for MYSQL database
      community.general.ufw:
        rule: allow
        port: 3306
        proto: tcp

    - name: Deploy basic index.html
      template:
        src: "~/IAC-2025/ansible/roles/web_server//templates/index.php.j2"
        dest: "/var/www/html/index.php"
        owner: "www-data"
        group: "www-data"
        mode: "0644"

    - name: restart apache
      service:
        name: apache2
        state: restarted